In [16]:
import warnings
warnings.filterwarnings("ignore")

In [24]:
import pandas as pd
from building_models.numerical_representation.encoders import EncodeSequences
from building_models.utils.utils_functions import UtilsFunctions

In [18]:
path_data = "../../processed_dataset/"

In [19]:
df_data = pd.read_csv(f"{path_data}processed_data/processed_dataset.csv")
df_data = df_data[["sequence", "label"]]
df_data.head(5)

                                            sequence  label
0  EKKSINECDLKGKKVLIRVDFNVPVKNGKITNDYRIRSALPTLKKV...      1
1  GHMARTVNLKGNPVTLVGPELKVGDRAPEAVVVTKDLQEKIVGGAK...      1
2  GHMEERVLGMPAVESNMFPLGKQAPPFALTNVIDGNVVRLEDVKSD...      1
3  GHMVEIGELAPDFELPDTELKKVKLSALKGKVVVLAFYPAAFTQVC...      1
4  GSSGSSGTEERLKEIEAKYDEIAKDWPKKVKHVLHEEHELELTRVQ...      1

In [20]:
df_errors = pd.read_csv(f"{path_data}processed_data/sequences_with_errors.csv")
df_errors = df_errors[["sequence"]]
df_errors.head(5)

                                            sequence
0  MAGQKIRIRLKAYDHEAIDASARKIVETVVRTGASVVGPVPLPTEK...
1  MAHKKAGGSTRNGRDSESKRLGVKRFGGESVLAGNIIVRQRGTKFH...
2  MAIDENKQKALAAALGQIEKQFGKGSIMRLGEDRSMDVETISTGSL...
3  MAKISKRRQAFAAKVDRQKLYAIEDALSLVKECASAKFDESIDVAV...
4  MARDIAAPPVPTNHQELISWVNEIAELTQPDAVVWCDGSEAEYERL...

In [21]:
df_unlabeled = pd.read_csv(f"{path_data}processed_data/unlabeled_data.csv")
df_unlabeled = df_unlabeled[["sequence"]]
df_unlabeled.head(5)

                                            sequence
0  MAAAAGRLLWSSVARHASAISRSISASTVLRPVASRRTCLTDILWS...
1  MAAAVGRLLRASVARHVSAIPWGISATAALRPAACGRTSLTNLLCS...
2  MAAKTGSQLERSISTIINVFHQYSRKYGHPDTLNKAEFKEMVNKDL...
3  MAALDAIREALPEPARDIKLNLQAVLQPGPLTPAQRWGVAVATAAA...
4  MAALKAGRGANWSLRAWRALGGIFWRKPPLLAPDLRALLTSGTPDS...

- Getting baseline representation

In [26]:
UtilsFunctions.make_directory(f"{path_data}encoded_data/one_hot")

In [30]:
for data in [(df_data, "full_data"), (df_errors, "error_data"), (df_unlabeled, "unlabeled_data")]:
    dataset = data[0]
    name_export = data[1]

    df_one_hot = EncodeSequences.encode_dataset(df=dataset, column_with_sequence="sequence", method="one_hot")
    df_one_hot = df_one_hot.merge(right=df_data, on="sequence")
    df_one_hot = df_one_hot.drop(columns=["is_canon"])
    df_one_hot.to_csv(f"{path_data}encoded_data/one_hot/{name_export}.csv", index=False)

In [31]:
UtilsFunctions.make_directory(f"{path_data}encoded_data/esm2_t6_8M_UR50D")

In [32]:
for data in [(df_data, "full_data"), (df_errors, "error_data"), (df_unlabeled, "unlabeled_data")]:
    dataset = data[0]
    name_export = data[1]

    df_embedding = EncodeSequences.get_embeddings(df=dataset, column_with_sequence="sequence")
    df_embedding = df_embedding.merge(right=df_data, on="sequence")
    df_embedding = df_embedding.drop(columns=["is_canon"])
    df_embedding.to_csv(f"{path_data}encoded_data/esm2_t6_8M_UR50D/{name_export}.csv", index=False)

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/95.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/775 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/31.4M [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/30.3M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/31.4M [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/93.0 [00:00<?, ?B/s]

Some weights of EsmModel were not initialized from the model checkpoint at /scratch/global_1/dmedina/sylphy/models/huggingface/facebook/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of EsmModel were not initialized from the model checkpoint at /scratch/global_1/dmedina/sylphy/models/huggingface/facebook/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of EsmModel were not initialized from the model checkpoint at /scratch/global_1/dmedina/sylphy/models/huggingface/facebook/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.