In [1]:
import warnings
import pandas as pd
warnings.filterwarnings("ignore")
from building_models.commons_functions.parsers_commons import ParsersCommons
from building_models.utils.constants import COLUMNS_TO_WORK
from building_models.utils.utils_functions import UtilsFunctions

#### Antioxidant protein dataset preprocessing and metadata generation

This script processes antioxidant protein data from multiple files within a single source, assigns labels using different rules depending on the file, handles duplicated sequences, and generates a structured dataset along with metadata.

- Overview
    - Task: Antioxidant protein classification dataset preparation
    - Source: PredAoDP dataset
    - Input: Multiple FASTA-like files containing protein sequences and metadata Excel file
    - Output: Processed dataset (CSV) and metadata file (JSON)
- Process:
    - Read protein sequences from multiple input files
    - Assign labels using different strategies (fixed labels, identifier-based rules, and index-based splits)
    - Standardize data by removing identifier columns
    - Concatenate all datasets into a single dataset
    - Check for duplicated sequences and label consistency
    - Concatenate consistent duplicates with unique sequences
    - Load and organize source metadata
    - Export processed data and metadata

- Auxiliary variables and functions

In [2]:
def add_label_based_on_id(id_value):
    if "non-antioxidant" in id_value:
        return 0
    else:
        return 1

In [3]:
path_export = "../../processed_dataset"
path_input = "../../raw_dataset"
metadata_file = "../../raw_dataset/raw_data_description.xlsx"
name_task = "antioxidant_classification"
name_source = "PredAoDP"

- Read docs

In [4]:
df_anti = ParsersCommons.read_fasta_doc(f"{path_input}/{name_source}/anti.txt")
df_anti["label"] = 1
df_anti = df_anti.drop(columns=["id"])
df_anti.head()

                                            sequence  label
0  MTKGILLGDKFPDFRAETNEGFIPSFYDWIGKDSWAILFSHPRDFT...      1
1  MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMN...      1
2  MAIALSSSSTITSITLQPKLKTIHGLGTVLPGYSVKSHFRSVSLRR...      1
3  MITSSKKIVSAMLSTSLWIGVASAAYAETTNVEAEGYSTIGGTYQD...      1
4  MANSGLWELITIGSAVRNVAKSYLKAEASSITAKQLYDASKITSSK...      1

In [5]:
df_Antioxident666 = ParsersCommons.read_fasta_doc(f"{path_input}/{name_source}/Antioxident666.txt")
df_Antioxident666["label"] = df_Antioxident666["id"].apply(add_label_based_on_id)
df_Antioxident666 = df_Antioxident666.drop(columns=["id"])
df_Antioxident666.head()

                                            sequence  label
0  MRSPSLAVAATTVLGLFSSSALAYYGNTTTVALTTTEFVTTCPYPT...      0
1  MRLRRLALFPGVALLLAAARLAAASDVLELTDDNFESRISDTGSAG...      0
2  MAPPQRHPQRSEQVLLLTLLGTLWGAAAAQIRYSIPEELEKGSFVG...      0
3  MSELSDIRREYTLGELHSEDVPNDPMDLFNAWLEVVRDSQIQDPTA...      0
4  MAGNAAVGVLALQGDVSEHISAFESAIQNLGLNIPVVPVRKAEQIL...      0

In [6]:
df_independent_dataset = ParsersCommons.read_fasta_doc(f"{path_input}/{name_source}/independent dataset.txt")
print(df_independent_dataset.shape)
df_independent_dataset_neg = df_independent_dataset[:392]
df_independent_dataset_pos = df_independent_dataset[392:]
df_independent_dataset_neg["label"] = 0
df_independent_dataset_pos["label"] = 1

df_independent_dataset = pd.concat([df_independent_dataset_neg, df_independent_dataset_pos], axis=0, ignore_index=True)
df_independent_dataset = df_independent_dataset.drop(columns=["id"])
df_independent_dataset.head()

(465, 2)

                                            sequence  label
0  MRSPSLAVAATTVLGLFSSSALAYYGNTTTVALTTTEFVTTCPYPT...      0
1  MRLRRLALFPGVALLLAAARLAAASDVLELTDDNFESRISDTGSAG...      0
2  MAPPQRHPQRSEQVLLLTLLGTLWGAAAAQIRYSIPEELEKGSFVG...      0
3  MSELSDIRREYTLGELHSEDVPNDPMDLFNAWLEVVRDSQIQDPTA...      0
4  MAGNAAVGVLALQGDVSEHISAFESAIQNLGLNIPVVPVRKAEQIL...      0

In [7]:
df_independent_dataset_2 = ParsersCommons.read_fasta_doc(f"{path_input}/{name_source}/Indpendent dataset.txt")
df_independent_dataset_2.head()

       id                                           sequence
0  anti_1  MTKGILLGDKFPDFRAETNEGFIPSFYDWIGKDSWAILFSHPRDFT...
1  anti_3  MAIALSSSSTITSITLQPKLKTIHGLGTVLPGYSVKSHFRSVSLRR...
2  anti_5  MANSGLWELITIGSAVRNVAKSYLKAEASSITAKQLYDASKITSSK...
3  anti_7  MSDLVNKKFPAGDYKFQYIAISQSDADSESCKMPQTVEWSKLISEN...
4  anti_8  MALLTIGDQFPEYDLTAVVGGDLSKVDAKQPDDYFTRVTSKDYEGK...

In [8]:
df_independent_dataset_2_anti = df_independent_dataset_2[df_independent_dataset_2["id"].str.startswith("anti")]
df_independent_dataset_2_nonanti = df_independent_dataset_2[~df_independent_dataset_2["id"].str.startswith("anti")]

In [9]:
df_independent_dataset_2_anti["label"] = 1
df_independent_dataset_2_nonanti["label"] = 0

df_independent_dataset_2 = pd.concat([df_independent_dataset_2_anti, df_independent_dataset_2_nonanti], 
                                     axis=0, ignore_index=True)
df_independent_dataset_2 = df_independent_dataset_2.drop(columns=["id"])

df_independent_dataset_2.head()

                                            sequence  label
0  MTKGILLGDKFPDFRAETNEGFIPSFYDWIGKDSWAILFSHPRDFT...      1
1  MAIALSSSSTITSITLQPKLKTIHGLGTVLPGYSVKSHFRSVSLRR...      1
2  MANSGLWELITIGSAVRNVAKSYLKAEASSITAKQLYDASKITSSK...      1
3  MSDLVNKKFPAGDYKFQYIAISQSDADSESCKMPQTVEWSKLISEN...      1
4  MALLTIGDQFPEYDLTAVVGGDLSKVDAKQPDDYFTRVTSKDYEGK...      1

In [10]:
df_nonanti = ParsersCommons.read_fasta_doc(f"{path_input}/{name_source}/nonanti.txt")
df_nonanti["label"] = 0
df_nonanti = df_nonanti.drop(columns=["id"])

df_nonanti.head()

                                            sequence  label
0  MERPYACPVESCDRRFSRSADLTRHIRIHTGQKPFQCRICMRNFSR...      0
1  MAPAEILNGKEISAQIRARLKNQVTQLKEQVPGFTPRLAILQVGNR...      0
2  MNLTELKNTPVSELITLGENMGLENLARMRKQDIIFAILKQHAKSG...      0
3  MKNLDCWVDNEEDIDVILKKSTILNLDINNDIISDISGFNSSVITY...      0
4  MFKVYGYDSNIHKCGPCDNAKRLLTVKKQPFEFINIMPEKGVFDDE...      0

- Concat data and check duplicates

In [11]:
df_concat = pd.concat([
    df_nonanti, 
    df_independent_dataset_2, 
    df_independent_dataset,
    df_anti,
    df_Antioxident666], ignore_index=True, axis=0)
df_concat.shape, df_concat["sequence"].unique().shape

((3007, 2), (2378,))

In [12]:
df_consistent_duplicates, df_errors, df_unique = ParsersCommons.processing_duplicated(
    df_concat, group_seq= "sequence",
    label_col= "label")
df_consistent_duplicates.shape, df_errors.shape, df_unique.shape

((571, 3), (0, 0), (1807, 2))

In [13]:
data_correct = pd.concat([df_consistent_duplicates, df_unique], axis=0, ignore_index=True)
data_correct = data_correct.drop(columns=["n_duplicates"])
data_correct.head()

                                            sequence  label
0  AFAGILADADITAALAACKAEGTFTHGVFFTKIGLKGKSAADIKKV...      0
1  GSASPTPPYLKWAESLHSLLDDQDGISLFRTFLKQEGCADLLDFWF...      0
2  LSADQISTVQASFDKVKGDPVGILYAVFKADPSIMAKFTQFAGKDL...      0
3  MAAAASTLASLSATAAAAAGKRLLLSSPSRSLSLSLASRGRIAVMP...      1
4  MAAAPPPPPPPQLQSSDPSTPPQETSQVRKGKKSRGAKKPRRAAAA...      0

- Reading metadata

In [14]:
metadata_file = ParsersCommons.read_metadata(metadata_file, name_source=name_source, columns_to_select=COLUMNS_TO_WORK)
metadata_file.head()

,name dataset,name source,type source,static-dynamic,license,reports constant updates,year of publication,last update date,download date,file format,protein format,category dataset,task,obtaining negative dataset,obtaining positive dataset,repository or server,publication,unit of measurement
47,anti.txt,PredAoDP,Dataset,Static,No information,No,2022,2022-11-15,2025-09-07,txt,"Sequence, UniProt ID",Enzyme/protein classification,Antioxidant,No information,"Sampling from UniProt, Previously published mo...",https://github.com/saeed344/PreAoDp/tree/maste...,https://www.sciencedirect.com/science/article/...,No information
48,Antioxident666.txt,PredAoDP,Dataset,Static,No information,No,2022,2022-11-15,2025-09-07,txt,"Sequence, UniProt ID",Enzyme/protein classification,Antioxidant,"Manually curated database, Sampling from UniProt","Sampling from UniProt, Previously published mo...",https://github.com/saeed344/PreAoDp/tree/maste...,https://www.sciencedirect.com/science/article/...,No information
49,independent dataset.txt,PredAoDP,Dataset,Static,No information,No,2022,2022-11-15,2025-09-07,txt,"Sequence, UniProt ID",Enzyme/protein classification,Antioxidant,"Manually curated database, Sampling from UniProt","Sampling from UniProt, Previously published mo...",https://github.com/saeed344/PreAoDp/tree/maste...,https://www.sciencedirect.com/science/article/...,No information
50,Indpendent dataset.txt,PredAoDP,Dataset,Static,No information,No,2022,2022-11-15,2025-09-07,txt,"Sequence, UniProt ID",Enzyme/protein classification,Antioxidant,"Manually curated database, Sampling from UniProt","Sampling from UniProt, Previously published mo...",https://github.com/saeed344/PreAoDp/tree/maste...,https://www.sciencedirect.com/science/article/...,No information
51,nonanti.txt,PredAoDP,Dataset,Static,No information,No,2022,2022-11-15,2025-09-07,txt,"Sequence, UniProt ID",Enzyme/protein classification,Antioxidant,"Manually curated database, Sampling from UniProt",No information,https://github.com/saeed344/PreAoDp/tree/maste...,https://www.sciencedirect.com/science/article/...,No information

In [15]:
dict_metadata = ParsersCommons.create_metadata_from_file(metadata_file)
dict_metadata

{'name dataset': 'anti.txt;Antioxident666.txt;independent dataset.txt;Indpendent dataset.txt;nonanti.txt',
 'name source': 'PredAoDP',
 'type source': 'Dataset',
 'static-dynamic': 'Static',
 'license': 'No information',
 'reports constant updates': 'No',
 'year of publication': 2022,
 'last update date': Timestamp('2022-11-15 00:00:00'),
 'download date': Timestamp('2025-09-07 00:00:00'),
 'file format': 'txt',
 'protein format': 'Sequence, UniProt ID',
 'category dataset': 'Enzyme/protein classification',
 'task': 'Antioxidant',
 'obtaining negative dataset': 'No information;Manually curated database, Sampling from UniProt',
 'obtaining positive dataset': 'Sampling from UniProt, Previously published model dataset;No information',
 'repository or server': 'https://github.com/saeed344/PreAoDp/tree/master/Data',
 'publication': 'https://www.sciencedirect.com/science/article/pii/S0169743922001344?via%3Dihub',
 'unit of measurement': 'No information',
 'number_of_sources': 5,
 'processing_date': '2026-08-01 19:42:33'}

In [16]:
dict_metadata['number_of_records'] = df_concat.shape[0]
dict_metadata['number_of_collected_sequences'] = df_concat.shape[0]
dict_metadata['number_of_unique_sequences'] = data_correct.shape[0]
dict_metadata['positive_examples'] = data_correct[data_correct["label"] == 1].shape[0]
dict_metadata['negative_examples'] = data_correct[data_correct["label"] == 0].shape[0]
dict_metadata['number_of_sequences_with_errors'] = df_errors.shape[0]
dict_metadata

{'name dataset': 'anti.txt;Antioxident666.txt;independent dataset.txt;Indpendent dataset.txt;nonanti.txt',
 'name source': 'PredAoDP',
 'type source': 'Dataset',
 'static-dynamic': 'Static',
 'license': 'No information',
 'reports constant updates': 'No',
 'year of publication': 2022,
 'last update date': Timestamp('2022-11-15 00:00:00'),
 'download date': Timestamp('2025-09-07 00:00:00'),
 'file format': 'txt',
 'protein format': 'Sequence, UniProt ID',
 'category dataset': 'Enzyme/protein classification',
 'task': 'Antioxidant',
 'obtaining negative dataset': 'No information;Manually curated database, Sampling from UniProt',
 'obtaining positive dataset': 'Sampling from UniProt, Previously published model dataset;No information',
 'repository or server': 'https://github.com/saeed344/PreAoDp/tree/master/Data',
 'publication': 'https://www.sciencedirect.com/science/article/pii/S0169743922001344?via%3Dihub',
 'unit of measurement': 'No information',
 'number_of_sources': 5,
 'processing_date': '2026-08-01 19:42:33',
 'number_of_records': 3007,
 'number_of_collected_sequences': 3007,
 'number_of_unique_sequences': 2378,
 'positive_examples': 365,
 'negative_examples': 2013,
 'number_of_sequences_with_errors': 0}

- Export data

In [17]:
UtilsFunctions.make_directory(f"{path_export}/{name_task}/{name_source}")
UtilsFunctions.export_json(f"{path_export}/{name_task}/{name_source}/metadata_{name_source}.json", dict_metadata)
data_correct.to_csv(f"{path_export}/{name_task}/{name_source}/processed_data.csv", index=False)